# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='isfavourite',
            field=models.BooleanField(default=False),
        ),
    ]
